print("Maths below :\n")

print("Addition: 8 + 3")
print(8 + 3)
print("Subtraction: 8 - 3")
print(8 - 3)
print("Multiplication: 8 * 3")
print(8 * 3)
print("Division: 8 / 3")
print(8 / 3)
print("Modulus: 8 % 3")
print(8 % 3)

print("\n____________________________________\n")
print("Power (exponent like Math.pow): 8 ** 3")
print(8 ** 3)
print("Power inbuilt function: pow(5, 4)")
print(pow(5, 4))
print("Absolute inbuilt function: abs(-48)")
print(abs(-48))
